### ISSUE TITLE
Question: Can we use this plugin with Cucumber

### ISSUE THREAD

**Issue by DeChrish** [badeball/cypress-parallel#2]
Feature files can be run in parallel with this plugin?

Error:
 npx cypress-parallel --node 1:5
Test file cypress\integration\hellow.feature wasn't distributed by the configured strategy

**Comment by badeball** [comment]
> Feature files can be run in parallel with this plugin?

Yes.

What does your configuration look like?

**Comment by Phx155** [comment]
@badeball i also have this issue, which configuration do you want to check?

**Comment by badeball** [comment]
I need a complete, but minimal example that allows me to run and observe the error myself.
