### ISSUE TITLE
!!!

### ISSUE THREAD

**Issue by DeChrish** [badeball/cypress-parallel#4]
![image](https://user-images.githubusercontent.com/6211294/168127456-2a5edea9-fcd3-4006-b378-8c5db66f4327.png)

**Comment by badeball** [comment]
Lmao... Have you by any chance added an custom, but empty strategy, as shown below?

```js
module.export = {
  /** @type {import("@badeball/cypress-parallel").UnweighedStrategy} */
  unweighedStrategy(weighedFiles, unweighedFiles, nodeCount) {
    // Implement me.
  },
};
```
