### ISSUE TITLE
Where we need to add?

### ISSUE THREAD

**Issue by DeChrish** [badeball/cypress-parallel#5]
Lmao... Have you by any chance added an custom, but empty strategy, as shown below?

module.export = {
  /** @type {import("@badeball/cypress-parallel").UnweighedStrategy} */
  unweighedStrategy(weighedFiles, unweighedFiles, nodeCount) {
    // Implement me.
  },
};

Q: Where we need to add?

My Plugin File>

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

 
  allureWriter(on, config)
  on('file:preprocessor', cucumber());
  on('before:browser:launch', (browser, args) => {
    if(browser.name =='chrome' && browser.isHeadless) {
      // headless no gpu
      args.push('--disable-gpu')
      // in vm container, shm size can be limited
      args.push('--disable-dev-shm-usage')
      args.push('--disable-infobars')
    }
  });
  on('task', {
    log (message) {
      console.log(message);     
      return null;
    }
  });
  return config
}

**Comment by badeball** [comment]
You have to provide me with a minimal example that illustrates the error.
